[package]
name = "erooster_core"
version = "0.1.0"
edition = "2021"
description = "An IMAP4v2 compatible mail server"
license = "Apache-2.0"
authors = ["MTRNord <mtrnord@nordgedanken.dev>"]
repository = "https://github.com/MTRNord/erooster/"
keywords = ["email", "imap", "smtp", "simple", "fast"]
categories = ["email", "network-programming"]
include = ["src/**/*", "build.rs", "migrations/**/*"]

[lib]
bench = false

[dependencies]
argon2 = { version = "0.4.1", features = ["std"] }
async-trait = "0.1.59"
base64 = "0.20.0"
bytes = "1.3.0"
cfg-if = "1.0.0"
color-eyre = "0.6.2"
futures = { version = "0.3.25", features = ["thread-pool"] }
mailparse = "0.13.8"
nom = "7.1.1"
opentelemetry-jaeger = { version = "0.17.0", features = [
    "tokio",
], optional = true }
owo-colors = "3.5.0"
rand_core = { version = "0.6.4", features = ["std"] }
rustls = "0.20.7"
serde = { version = "1.0.150", features = ["derive"] }
serde_yaml = "0.9.14"
simdutf8 = { version = "0.1.4" }
sqlx = { version = "0.6.2", features = ["postgres", "runtime-tokio-rustls"] }
sys-info = "0.9.1"
tokio = { version = "1.22.0", features = ["full"] }
tokio-rustls = { version = "0.23.4", features = ["tls12"] }
tokio-stream = { version = "0.1.11", features = ["net", "io-util"] }
tokio-util = { version = "0.7.4", features = ["full"] }
tracing = "0.1.37"
tracing-error = "0.2.0"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
url = "2.3.1"
webpki-roots = "0.22.6"
secrecy = "0.8.0"

[build-dependencies]
vergen = { git = "https://github.com/erooster-mail/vergen.git", rev = "e9502aad12f9fa0bfee7c9ee6581f759901b7426" }

[dependencies.maildir]
version = "0.6.1"
git = "https://github.com/erooster-mail/maildir.git"
#rev = "179625c3cc15212fb26eca5b819f7fe0d6f802e1"
branch = "MTRNord/clippy"
optional = true

[features]
default = ["maildir"]
maildir = ["dep:maildir", "maildir/mmap"]
jaeger = ["dep:opentelemetry-jaeger"]

#[profile.release]
#debug = true

[dev-dependencies]
convert_case = "0.6.0"
criterion = { version = "0.4.0", features = ["async_tokio"] }
enum-iterator = "1.2.0"
enum-display-derive = "0.1.1"
