[package]
name = "erooster"
version = "0.1.0"
edition = "2021"
description = "An IMAP4v2 compatible mail server"
license = "Apache-2.0"
authors = ["MTRNord <mtrnord@nordgedanken.dev>"]
repository = "https://github.com/MTRNord/erooster/"
keywords = ["email", "imap", "smtp", "simple", "fast"]
categories = ["email", "network-programming"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
bench = false
name = "erooster"
path = "src/main.rs"

[dependencies]
erooster_core = { version = "0.1.0", path = "../erooster_core" }
erooster_smtp = { version = "0.1.0", path = "../erooster_smtp" }
erooster_imap = { version = "0.1.0", path = "../erooster_imap" }
erooster_web = { version = "0.1.0", path = "../erooster_web" }
cfg-if = "1.0.0"
clap = { version = "4.1.6", features = [
    "derive",
    "color",
    "suggestions",
    "env",
] }
color-eyre = "0.6.2"
opentelemetry = { version = "0.19.0", features = ["metrics", "rt-tokio"] }
opentelemetry-jaeger = { version = "0.18.0", features = [
    "rt-tokio",
], optional = true }
serde = { version = "1.0.179", features = ["derive"] }
tokio = { version = "1.25.0", features = ["rt", "rt-multi-thread", "signal"] }
tracing = "0.1.37"
tracing-error = "0.2.0"
tracing-opentelemetry = { version = "0.19.0", optional = true }
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
tracing-futures = { version = "0.2.5", features = ["tokio"] }

[features]
default = []
jaeger = ["dep:opentelemetry-jaeger", "dep:tracing-opentelemetry"]

[build-dependencies]
clap = { version = "4.1.6", features = [
    "derive",
    "color",
    "suggestions",
    "env",
] }
clap_mangen = "0.2.8"
vergen = "7.5.1"
