[package]
name = "erooster"
version = "0.1.0"
edition = "2021"
description = "An IMAP4v2 compatible mail server"
license = "Apache-2.0"
authors = ["MTRNord <mtrnord@nordgedanken.dev>"]
repository = "https://github.com/MTRNord/erooster/"
keywords = ["email", "imap", "smtp", "simple", "fast"]
categories = ["email", "network-programming"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
bench = false
name = "erooster"
path = "src/main.rs"

[dependencies]
erooster_core = { version = "0.1.0", path = "../erooster_core" }
erooster_smtp = { version = "0.1.0", path = "../erooster_smtp" }
erooster_imap = { version = "0.1.0", path = "../erooster_imap" }
erooster_web = { version = "0.1.0", path = "../erooster_web" }
cfg-if = "1.0"
clap = { version = "3.1", features = ["derive", "color", "suggestions", "env"] }
color-eyre = "0.6"
opentelemetry = { version = "0.17", features = ["metrics", "rt-tokio"] }
opentelemetry-jaeger = { version = "0.16", features = [
    "rt-tokio",
], optional = true }
sentry = { version = "0.27", default-features = false, features = [
    "tracing",
    "backtrace",
    "contexts",
    "panic",
    "ureq",
] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.21", features = ["full"] }
tracing = "0.1"
tracing-error = "0.2"
tracing-opentelemetry = "0.17"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
auditable = "0.2"

[features]
default = []
jaeger = ["dep:opentelemetry-jaeger"]

[build-dependencies]
clap = { version = "3.1", features = ["derive", "color", "suggestions", "env"] }
clap_mangen = "0.1"
vergen = "7.4"
auditable-build = "0.2"
