# SPDX-FileCopyrightText: 2023 MTRNord
#
# SPDX-License-Identifier: CC0-1.0

name: Spell Check
on:
  push:
    branches:
      - "main"
  pull_request:

# Declare default permissions as read only.
permissions: read-all

jobs:
  run:
    permissions:
      contents: read # for actions/checkout to fetch code
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: block
          allowed-endpoints: >
            github.com:443
            objects.githubusercontent.com:443
            release-assets.githubusercontent.com:443
        env:
          USER: runner
      - name: Checkout Actions Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Check spelling
        uses: crate-ci/typos@37bb98842b0d8c4ffebdb75301a13db0267cef89 # v1.47.2
        with:
          config: ${{github.workspace}}/_typos.toml
